#!/bin/bash

cd src
#../../cppcheck/cppcheck --enable=all --force -j 5 -v -I /usr/include -I /usr/include/c++/4.4 . 1>../makecheck.txt 2>../makecheck_err.txt
../../cppcheck/cppcheck --enable=style --enable=information --enable=unusedFunction --force -j 5 -v . 1>../check1.txt 2>../check2.txt
